### ISSUE TITLE
20210324 ERROR and TODO

### ISSUE THREAD

**Issue by leeleelee3264** [leeleelee3264/twitter_project#1]
### error 
- [x] path가 crawl/img 로 들어가 있는데 그게 아니라 img가 밖으로 나와야 한다. 
- [x] duplicate status 충복트윗을 어떻게 해야 하나 생각해야 한다. --> 앞에 숫자를 쓰거나 해야겠음. 아니면 중복이어도 트윗되게
- [x] 패스도 지금 어떤 부분은 windows 기준으로 써있다. 

### TODO
- [x] 이미지 저장이 되면 commit 작업도 해야 한다. 안그럼 repo에 남지를 않는다. (그럼 커밋하고 트위터 올리기를 해야하나??) 
- [x] tweetpy 이미지 올리기 해보기 --> 근데 얘가 날짜마다 만들어주는데 그럼 media_id가 달라서 중복 안 걸릴 것 같기도 함
- [x] 파일 이름에 공백이나 특수 문자 들어가면 바꿔줘야 함 --> 아 근데 그럼 또 이미지랑 타이틀을 뭘로 맵핑하냐 --> dict 이 아니라 list 로 관리해야하나 싶음 list(dict('title', 'date'))

**Comment by leeleelee3264** [comment]
finish
